version: '3.7'

x-base-config: &base-config
  network_mode: host
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: '5'
      compress: 'true'

services:
  minio:
    image: quay.io/minio/minio:latest
    command: 
      - server
      - --console-address
      - :9001
      - --address
      - :8787
      - http://127.0.0.1/data{1...2}
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: qwer1234
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    volumes:
      - type: volume
        source: data1
        target: /data1
      - type: volume
        source: data2
        target: /data2
    <<: *base-config

  envoy:
      image: envoyproxy/envoy:v1.23-latest
      command:
        - --config-path /etc/envoy/envoy.yml
        - --log-level debug
      volumes:
        - type: bind
          source: ./envoy.yml
          target: /etc/envoy/envoy.yml
        - type: bind
          source: ./certs
          target: /certs
      depends_on:
        - minio
      <<: *base-config

volumes:
  data1:
  data2:
