version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" http://minio{1...2}.game-soul-swe.com/data{1...2}
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: qwer1234
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    volumes:
      - type: volume
        source: data1
        target: /data1
      - type: volume
        source: data2
        target: /data2
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
        compress: 'true'

volumes:
  data1:
  data2:
