x-base-config: &base-config
  network_mode: host
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: '5'
      compress: 'true'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-10-13T13-34-11Z
    command: 
      - server
      - --console-address
      - :9001
      - --address
      - :8787
      - ${MINIO_HOST_URLS:?err}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?err}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?err}

      MINIO_PROMETHEUS_AUTH_TYPE: public # Do not require that scraping clients authenticate their requests.
      # MINIO_PROMETHEUS_URL: http://103.147.199.7:9090
      # MINIO_PROMETHEUS_JOB_ID: minio-lom

    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    volumes:
      - type: volume
        source: data1
        target: /data1
      - type: volume
        source: data2
        target: /data2
    <<: *base-config

  envoy:
      image: envoyproxy/envoy:v1.32-latest
      command:
        - --config-path /etc/envoy/envoy.yaml
        - --log-level debug
      volumes:
        - type: bind
          source: ./envoy.yaml
          target: /etc/envoy/envoy.yaml
        - type: bind
          source: ./certs
          target: /certs
      depends_on:
        - minio
      <<: *base-config

volumes:
  data1:
  data2:
