version: '3.7'

services:
  ovpn:
    image: kylemanna/openvpn:2.4
    volumes:
      - ./data:/etc/openvpn
      - type: volume
        source: ovpn-data
        target: /etc/openvpn
    ports:
      - '1194:1194/udp'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
        compress: 'true'

volumes:
  ovpn-data: